name: cram
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_5
  - ca-certificates=2024.3.11=h06a4308_0
  - certifi=2024.2.2=py311h06a4308_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.4.99=0
  - cuda-runtime=12.1.0=0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py311h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py311hc9b5ff0_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py311h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.3=py311h06a4308_0
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.9.0.20=0
  - libcurand=10.3.5.119=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.3=py311h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.8=py311h5eee18b_0
  - mkl_random=1.2.4=py311hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py311h06a4308_0
  - numpy=1.26.4=py311h08b1b3b_0
  - numpy-base=1.26.4=py311hf175353_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.13=h7f8727e_0
  - pillow=10.2.0=py311h5eee18b_0
  - pip=23.3.1=py311h06a4308_0
  - python=3.11.8=h955ad1f_0
  - pytorch=2.2.1=py3.11_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py311h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py311h06a4308_1
  - setuptools=68.2.2=py311h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - sympy=1.12=py311h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=2.2.1=py311_cu121
  - torchtriton=2.2.0=py311
  - torchvision=0.17.1=py311_cu121
  - typing_extensions=4.9.0=py311h06a4308_1
  - urllib3=2.1.0=py311h06a4308_0
  - wheel=0.41.2=py311h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
    - aiohttp==3.9.3
    - aiosignal==1.3.1
    - antlr4-python3-runtime==4.9.3
    - appdirs==1.4.4
    - attrs==23.2.0
    - click==8.1.7
    - cramming==0.1.0
    - datasets==2.18.0
    - dill==0.3.8
    - docker-pycreds==0.4.0
    - einops==0.7.0
    - evaluate==0.4.1
    - frozenlist==1.4.1
    - fsspec==2024.2.0
    - gitdb==4.0.11
    - gitpython==3.1.42
    - huggingface-hub==0.21.4
    - hydra-core==1.3.2
    - joblib==1.3.2
    - multidict==6.0.5
    - multiprocess==0.70.16
    - omegaconf==2.3.0
    - packaging==24.0
    - pandas==2.2.1
    - protobuf==4.25.3
    - psutil==5.9.8
    - pyarrow==15.0.2
    - pyarrow-hotfix==0.6
    - pynvml==11.5.0
    - python-dateutil==2.9.0.post0
    - pytz==2024.1
    - regex==2023.12.25
    - responses==0.18.0
    - safetensors==0.4.2
    - scikit-learn==1.4.1.post1
    - scipy==1.12.0
    - sentry-sdk==1.42.0
    - setproctitle==1.3.3
    - six==1.16.0
    - smmap==5.0.1
    - threadpoolctl==3.3.0
    - tokenizers==0.15.2
    - tqdm==4.66.2
    - transformers==4.38.2
    - tzdata==2024.1
    - wandb==0.16.4
    - xxhash==3.4.1
    - yarl==1.9.4
    - zstandard==0.22.0
prefix: /cmlscratch/jonas0/miniconda3/envs/cram
